# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    # Run the auto-generation script after the package is installed
    # but BEFORE Sphinx starts building the docs.
    post_install:
      - python scripts/generate_docs.py

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# If you need to install your package to build docs (required for autodoc)
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements: []